# Generated by Django 3.1.5 on 2021-01-19 00:56

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='entries',
            name='api_entries_metric__3d4b95_btree',
        ),
        migrations.RenameField(
            model_name='entries',
            old_name='metric_id',
            new_name='metric',
        ),
        migrations.RenameField(
            model_name='entries',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='metrics',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddIndex(
            model_name='entries',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['metric_id', 'user_id'], name='api_entries_metric__41a6bc_btree'),
        ),
    ]
